"""fix sqlalchemy's mapper error occuring between ChatRoom and base ChatHistory model

Revision ID: 02542b802d02
Revises: 6ee312dbbf2f
Create Date: 2024-08-19 16:43:00.390776

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "02542b802d02"
down_revision: Union[str, None] = "6ee312dbbf2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("room_uuid", sa.UUID(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column(
            "sent_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["room_uuid"],
            ["chat_rooms.room_uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "openai_chat_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role", sa.String(length=15), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["chat_history.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("openai_chat_histories")
    op.drop_table("chat_histories")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "openai_chat_histories",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "role", sa.VARCHAR(length=15), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["chat_histories.id"], name="openai_chat_histories_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="openai_chat_histories_pkey"),
    )
    op.create_table(
        "chat_histories",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("room_uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("message", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "sent_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["room_uuid"],
            ["chat_rooms.room_uuid"],
            name="chat_histories_room_uuid_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="chat_histories_pkey"),
    )
    op.drop_table("openai_chat_history")
    op.drop_table("chat_history")
    # ### end Alembic commands ###
