"""refactor: instead of hardcoding LLMs in ai service, provide columns for ai models in ApiProvider model

Revision ID: 06fd6fcc3faa
Revises: eef02938b325
Create Date: 2024-09-08 14:18:53.882320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06fd6fcc3faa'
down_revision: Union[str, None] = 'eef02938b325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_providers', sa.Column('ai_models', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_providers', 'ai_models')
    # ### end Alembic commands ###
