"""Rename ApiKey's ai_model column to api_provider

Revision ID: 090f98593afb
Revises: 24dfcbf76390
Create Date: 2024-06-11 19:44:09.164689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '090f98593afb'
down_revision: Union[str, None] = '24dfcbf76390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('api_provider', sa.String(length=15), nullable=False))
    op.drop_constraint('api_keys_ai_model_key', 'api_keys', type_='unique')
    op.drop_constraint('api_keys_ai_model_user_id_key', 'api_keys', type_='unique')
    op.create_unique_constraint(None, 'api_keys', ['api_provider'])
    op.create_unique_constraint(None, 'api_keys', ['api_provider', 'user_id'])
    op.drop_column('api_keys', 'ai_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('ai_model', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'api_keys', type_='unique')
    op.drop_constraint(None, 'api_keys', type_='unique')
    op.create_unique_constraint('api_keys_ai_model_user_id_key', 'api_keys', ['ai_model', 'user_id'])
    op.create_unique_constraint('api_keys_ai_model_key', 'api_keys', ['ai_model'])
    op.drop_column('api_keys', 'api_provider')
    # ### end Alembic commands ###
