"""Fix security bug by adding missing is_passphrase column

Revision ID: 42535f75adbd
Revises: b82c5935ddf5
Create Date: 2024-06-13 14:50:04.327605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42535f75adbd'
down_revision: Union[str, None] = 'b82c5935ddf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_passphrase', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_passphrase')
    # ### end Alembic commands ###
