"""recreate user model

Revision ID: 5d7db8bddb2a
Revises: f0ed3d7b9bfc
Create Date: 2024-06-23 19:55:52.875581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d7db8bddb2a'
down_revision: Union[str, None] = 'f0ed3d7b9bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_keys')
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    op.drop_column('users', 'is_passphrase')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_passphrase', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_email_verified')
    op.create_table('api_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('api_provider', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='api_keys_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='api_keys_pkey'),
    sa.UniqueConstraint('api_provider', 'user_id', name='api_keys_api_provider_user_id_key'),
    sa.UniqueConstraint('api_provider', name='api_keys_api_provider_key')
    )
    # ### end Alembic commands ###
