"""feat: extend ChatHistory model by adding 'image_url' column

Revision ID: 671093311f12
Revises: b8a0d0142737
Create Date: 2024-11-05 17:58:35.473510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '671093311f12'
down_revision: Union[str, None] = 'b8a0d0142737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'image_url')
    # ### end Alembic commands ###
