"""create relationship between: user -> api_key and api_key -> user, api_provider

Revision ID: 7a1653910ba6
Revises: b6cfa25e1601
Create Date: 2024-07-02 19:37:41.308729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a1653910ba6'
down_revision: Union[str, None] = 'b6cfa25e1601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
