"""feat: extend model enum by adding gemini

Revision ID: b8a0d0142737
Revises: 06fd6fcc3faa
Create Date: 2024-10-26 10:15:41.224704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'b8a0d0142737'
down_revision: Union[str, None] = '06fd6fcc3faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'aimodelenum', ['gpt_4', 'gpt_4_turbo', 'gpt_4o', 'gpt_4o_mini', 'gpt_3_5_turbo', 'gemini_1_5_flash', 'gemini_1_5_flash_8b', 'gemini_1_5_pro', 'gemini_1_0_pro'],
                        [TableReference(table_schema='public', table_name='chat_history', column_name='ai_model')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'aimodelenum', ['gpt_4', 'gpt_4_turbo', 'gpt_4o', 'gpt_4o_mini', 'gpt_3_5_turbo'],
                        [TableReference(table_schema='public', table_name='chat_history', column_name='ai_model')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
