"""feat: extend ChatRoom model by adding cascade option

Revision ID: dc42e8cb3713
Revises: f9487af4c63f
Create Date: 2024-08-25 15:39:38.719584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc42e8cb3713'
down_revision: Union[str, None] = 'f9487af4c63f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
