"""refactor: instead of using JTI, use one model for chat history

Revision ID: eef02938b325
Revises: dc42e8cb3713
Create Date: 2024-09-05 16:57:11.946055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eef02938b325'
down_revision: Union[str, None] = 'dc42e8cb3713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('gpt_4', 'gpt_4_turbo', 'gpt_4o', 'gpt_4o_mini', 'gpt_3_5_turbo', name='aimodelenum').create(op.get_bind())
    sa.Enum('user', 'assistant', name='roleenum').create(op.get_bind())
    op.drop_table('openai_chat_history')
    op.add_column('chat_history', sa.Column('api_provider_id', sa.Integer(), nullable=False))
    op.add_column('chat_history', sa.Column('role', postgresql.ENUM('user', 'assistant', name='roleenum', create_type=False), nullable=False))
    op.add_column('chat_history', sa.Column('ai_model', postgresql.ENUM('gpt_4', 'gpt_4_turbo', 'gpt_4o', 'gpt_4o_mini', 'gpt_3_5_turbo', name='aimodelenum', create_type=False), nullable=False))
    op.add_column('chat_history', sa.Column('custom_instructions', sa.String(), nullable=False))
    op.create_foreign_key(None, 'chat_history', 'api_providers', ['api_provider_id'], ['id'])
    op.drop_column('chat_history', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.drop_column('chat_history', 'custom_instructions')
    op.drop_column('chat_history', 'ai_model')
    op.drop_column('chat_history', 'role')
    op.drop_column('chat_history', 'api_provider_id')
    op.create_table('openai_chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('ai_model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('custom_instructions', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['chat_history.id'], name='openai_chat_history_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='openai_chat_history_pkey')
    )
    sa.Enum('user', 'assistant', name='roleenum').drop(op.get_bind())
    sa.Enum('gpt_4', 'gpt_4_turbo', 'gpt_4o', 'gpt_4o_mini', 'gpt_3_5_turbo', name='aimodelenum').drop(op.get_bind())
    # ### end Alembic commands ###
