"""add missing passphrase_salt column

Revision ID: f0ed3d7b9bfc
Revises: 42535f75adbd
Create Date: 2024-06-16 20:36:13.237804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ed3d7b9bfc'
down_revision: Union[str, None] = '42535f75adbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passphrase_salt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passphrase_salt')
    # ### end Alembic commands ###
