"""feat: extend the OpenAiChatHistory model by adding the 'ai_model' and 'custom_instructions' columns

Revision ID: f9487af4c63f
Revises: 02542b802d02
Create Date: 2024-08-21 15:06:11.375392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9487af4c63f'
down_revision: Union[str, None] = '02542b802d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('openai_chat_history', sa.Column('ai_model', sa.String(), nullable=False))
    op.add_column('openai_chat_history', sa.Column('custom_instructions', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('openai_chat_history', 'custom_instructions')
    op.drop_column('openai_chat_history', 'ai_model')
    # ### end Alembic commands ###
